spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking_api
    username: root
    password: *****
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
redis:
  host: localhost
  post: 6379
springdoc:
  api-docs:
    version: openapi_3_1
  show-actuator: true
  cache:
    disabled: true